# Generated by Django 5.1 on 2024-10-27 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='URLAnalytics',
        ),
    ]
