# Generated by Django 5.1 on 2024-10-27 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shortner', '0002_delete_urlanalytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(max_length=512)),
                ('referrer', models.CharField(blank=True, max_length=2048, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('access_count', models.PositiveIntegerField(default=1)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='shortner.shortnedurl')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['url'], name='analytics_u_url_id_b653d4_idx'), models.Index(fields=['timestamp'], name='analytics_u_timesta_ad4018_idx')],
            },
        ),
    ]
